on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
        SLACK_MESSAGE: "teste"
